### ISSUE TITLE
Can't Upload more than 2 plates

### ISSUE THREAD

**Issue by arhyneRWU** [DaniFlat/qRAT#3]
Hello,

UPDATED

Appears to be a bug in my multi-plate.  There is no error logging that i can see on the web interface that allows me to see what is causing the error.  Likely something going on with the plate that could use some cleaning. 

I have tried this on your server and also on the standalone version on a PC.

**Comment by DaniFlat** [comment]
Hi,
thank you for letting me know. It's good that you've already tracked down the problem a bit. Without an error message, it's hard to say what exactly is triggering the issue. But best make sure that all plates have the same column names and avoid spaces and special characters in the sample and gene names. If the problem persists, feel free to send me the corresponding files and I'll check if the problem is in the data processing.
